version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
  app:
    build: .
    command: ["scavengr-golang"]
    environment:
      - PORT=8080
    volumes:
      - .:/go/src/app
    ports:
      - "3000:8080"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
